// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ChromecastPlayerReloaded = require("chromecast-player-reloaded");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -889544535,
    "position"
  ],
  /* tuple */[
    100394802,
    "status"
  ],
  /* tuple */[
    169348974,
    "playing"
  ],
  /* tuple */[
    240232876,
    "closed"
  ]
];

function eventToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function eventFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

var player = ChromecastPlayerReloaded();

function launchPlayer(param, param$1) {
  player.launch(param, param$1);
  return /* () */0;
}

function attachPlayer(param, param$1) {
  player.attach(param, param$1);
  return /* () */0;
}

exports.eventToJs = eventToJs;
exports.eventFromJs = eventFromJs;
exports.player = player;
exports.launchPlayer = launchPlayer;
exports.attachPlayer = attachPlayer;
/* player Not a pure module */
