// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function cb(f) {
  return (function (err, result) {
      if (err !== undefined) {
        if (result !== undefined) {
          return Pervasives.invalid_arg("Callback arguments invalid");
        } else {
          return Curry._1(f, /* Error */Block.__(1, [Caml_option.valFromOption(err)]));
        }
      } else if (result !== undefined) {
        return Curry._1(f, /* Ok */Block.__(0, [Caml_option.valFromOption(result)]));
      } else {
        return Pervasives.invalid_arg("Callback arguments invalid");
      }
    });
}

exports.cb = cb;
/* No side effect */
