// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Dotenv = require("dotenv");
var Process = require("process");

Dotenv.config(undefined);

var env = Process.env;

var port = env["EXPRESS_PORT"];

exports.env = env;
exports.port = port;
/*  Not a pure module */
