// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/lib/js/src/Json_decode.bs.js");

function make(json) {
  return /* record */[
          /* command */Json_decode.field("command", Json_decode.string, json),
          /* payload */Json_decode.field("payload", Json_decode.string, json)
        ];
}

var Command = /* module */[/* make */make];

exports.Command = Command;
/* No side effect */
