// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Chromecast$CastServer = require("../utils/Chromecast.bs.js");

function launch(payload) {
  Chromecast$CastServer.Methods[/* launch */0](payload).then((function (result) {
          console.log("-->", result[0]);
          return Promise.resolve(/* () */0);
        }));
  return /* () */0;
}

Chromecast$CastServer.Methods[/* attach */1](/* () */0).then((function (result) {
        if (result.tag) {
          console.log("-->", result[0]);
        } else {
          Chromecast$CastServer.Methods[/* play */2](result[0]).then((function (player) {
                  if (player.tag) {
                    console.log("Error", player[0]);
                  } else {
                    console.log("Status", player[0]);
                  }
                  return Promise.resolve(/* () */0);
                }));
        }
        return Promise.resolve(/* () */0);
      }));

Chromecast$CastServer.Methods[/* attach */1](/* () */0).then((function (result) {
        if (result.tag) {
          console.log("-->", result[0]);
        } else {
          Chromecast$CastServer.Methods[/* pause */3](result[0]).then((function (player) {
                  if (player.tag) {
                    console.log("Error", player[0]);
                  } else {
                    console.log("Status", player[0]);
                  }
                  return Promise.resolve(/* () */0);
                }));
        }
        return Promise.resolve(/* () */0);
      }));

var play = /* () */0;

var pause = /* () */0;

exports.launch = launch;
exports.play = play;
exports.pause = pause;
/*  Not a pure module */
